added cache support , fixed anykernel paths , set custom name in kernel

diff --git a/.github/workflows/build_crom_kernel_n3.yml b/.github/workflows/build_crom_kernel_n3.yml
--- a/.github/workflows/build_crom_kernel_n3.yml
+++ b/.github/workflows/build_crom_kernel_n3.yml
@@ -89,27 +89,27 @@ jobs:
             echo "BUILD_METHOD=gki" >> $GITHUB_ENV
           fi
 
-      # - name: Check Disk Space
-      #   run: df -h
+      - name: Check Disk Space
+        run: df -h
 
-      # - name: Maximize Build Space
-      #   uses: easimon/maximize-build-space@master
-      #   with:
-      #     root-reserve-mb: 8192
-      #     temp-reserve-mb: 2048
-      #     remove-dotnet: 'true'
-      #     remove-android: 'true'
-      #     remove-haskell: 'true'
-      #     remove-codeql: 'true'
+      - name: Maximize Build Space
+        uses: easimon/maximize-build-space@master
+        with:
+          root-reserve-mb: 8192
+          temp-reserve-mb: 2048
+          remove-dotnet: 'true'
+          remove-android: 'true'
+          remove-haskell: 'true'
+          remove-codeql: 'true'
 
-      # - name: Create and Enable 3G Swap
-      #   run: |
-      #     sudo swapoff -a
-      #     sudo fallocate -l 3G /swapfile
-      #     sudo chmod 600 /swapfile
-      #     sudo mkswap /swapfile
-      #     sudo swapon /swapfile
-      #     free -h
+      - name: Create and Enable 3G Swap
+        run: |
+          sudo swapoff -a
+          sudo fallocate -l 3G /swapfile
+          sudo chmod 600 /swapfile
+          sudo mkswap /swapfile
+          sudo swapon /swapfile
+          free -h
 
       - name: Set Cache Environment
         run: |
@@ -167,29 +167,29 @@ jobs:
           sudo apt install -y libelf-dev ccache llvm lld
           sudo apt update -qq
 
-      # - name: Restore Ccache
-      #   uses: actions/cache@v3
-      #   with:
-      #     path: ${{ env.CCACHE_DIR }}
-      #     key: ccache-${{ runner.os }}-${{ github.ref_name }}-${{ github.event.inputs.FILE }}-${{ env.BUILD_METHOD }}-${{ github.event.inputs.FAST_BUILD == 'true' && 'alpha' || 'beta' }}-15
+      - name: Restore Ccache
+        uses: actions/cache@v3
+        with:
+          path: ${{ env.CCACHE_DIR }}
+          key: ccache-${{ runner.os }}-${{ github.ref_name }}-${{ github.event.inputs.FILE }}-${{ env.BUILD_METHOD }}-${{ github.event.inputs.FAST_BUILD == 'true' && 'alpha' || 'beta' }}-15
 
-      # - name: Initialize Ccache
-      #   run: |
-      #     INIT_FLAG="${{ env.CCACHE_DIR }}/.ccache_initialized"
-      #     if command -v ccache >/dev/null 2>&1; then
-      #       if [ ! -f "$INIT_FLAG" ]; then
-      #         echo "Initializing ccache (${{ env.CCACHE_DIR }})..."
-      #         mkdir -p "${{ env.CCACHE_DIR }}"
-      #         ccache -M ${{ env.CCACHE_MAXSIZE }}
-      #         touch "$INIT_FLAG"
-      #         echo "ccache initialization complete"
-      #       else
-      #         echo "ccache already initialized, skipping"
-      #       fi
-      #     else
-      #       echo "ccache not installed, skipping"
-      #     fi
-      #     ccache -s
+      - name: Initialize Ccache
+        run: |
+          INIT_FLAG="${{ env.CCACHE_DIR }}/.ccache_initialized"
+          if command -v ccache >/dev/null 2>&1; then
+            if [ ! -f "$INIT_FLAG" ]; then
+              echo "Initializing ccache (${{ env.CCACHE_DIR }})..."
+              mkdir -p "${{ env.CCACHE_DIR }}"
+              ccache -M ${{ env.CCACHE_MAXSIZE }}
+              touch "$INIT_FLAG"
+              echo "ccache initialization complete"
+            else
+              echo "ccache already initialized, skipping"
+            fi
+          else
+            echo "ccache not installed, skipping"
+          fi
+          ccache -s
 
       - name: Install Repo Tool
         run: |
@@ -202,45 +202,6 @@ jobs:
           mkdir kernel_workspace && cd kernel_workspace
           repo init -u https://github.com/darklord4567/test.git -m ${{ github.event.inputs.FILE }}.xml --depth=1
           repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
-
-      # - name: Copy Build Configuration
-      #   run: |
-      #     echo "pwd cmd"
-      #     pwd
-      #     echo "ls cmd"
-      #     ls
-      #     echo "cd kernel_workspace CMD!!!!!!!!!"
-      #     cd kernel_workspace
-      #     echo "pwd cmd!!!!!!!!!!!!!!!"
-      #     pwd
-      #     echo "ls cmd!!!!!!!!!!!!!!!!!"
-      #     ls
-      #     git clone https://github.com/darklord4567/kerenel_build_n3.git build_config
-      #     cp -v build_config/build.config.oplus6983 kernel-5.10/
-      #     echo "cd kernel-5.10 cmd"
-      #     cd kernel-5.10
-      #     echo "ls cmd"
-      #     ls
-      #     echo "pwd cmd"
-      #     pwd
-      #     echo "validate the file"
-      #     ls -ls kernel_workspace/kernel-5.10/build.config.oplus6983
-      - name: Copy Build Configuration
-        run: |
-          git clone https://github.com/darklord4567/kerenel_build_n3.git kernel_workflow
-          cp -v kernel_workflow/build.config.oplus6983 kernel_workspace/kernel-5.10/
-          echo "ls cmd!!!!!!!!!"
-          ls
-          echo "pwd cmd!!!!!!!!!!!"
-          pwd
-          echo "cd kernel_workspace/kernel-5.10 cmd!!!!!!!!!!"
-          cd kernel_workspace/kernel-5.10
-          echo "ls cmd!!!!!!!!!"
-          ls
-          echo "pwd cmd!!!!!!!!!!!"
-          pwd
-          echo "validate the file"
-          ls -ls build.config.oplus6983
 
 
       - name: Add in bash.rc
@@ -285,112 +246,53 @@ jobs:
           echo "rm -rf kernel_module"
           rm -rf kernel_module
           
-      - name: Create thermal Makefile
+
+      # Custom kernel suffix
+      - name: Custom Kernel Suffix if set
+        if: ${{ github.event.inputs.SUFFIX != '' }}
         run: |
-          echo "pwd"
-          pwd
-          echo "ls"
-          ls
-          echo "cd kernel_workspace"
           cd kernel_workspace
-          echo "pwd"
-          pwd
-          echo "ls"
-          ls
-          echo "cd & make file"
-          cd vendor/oplus/kernel/cpu/thermal && \touch Makefile && \
-          echo "obj-y += horae_shell_temp" > Makefile && \
-          echo "obj-y += oplus_ipa_thermal" >> Makefile
-          echo "THERMAL MAKEFILE!!!!!!!!!!!!"
-          echo "pwd"
-          pwd
-          echo "ls"
-          ls
-          cat Makefile
+          SUFFIX="${{ github.event.inputs.SUFFIX }}"
+          ANDROID_VERSION="${{ env.ANDROID_VERSION }}"
+          FAST_BUILD="${{ github.event.inputs.FAST_BUILD }}"
 
-      - name: Create Makefile in fingerprint mtk
-        run: |
-          echo "pwd"
-          pwd
-          echo "ls"
-          ls
-          echo "cd to mtk !!!!!!!!"
-          cd kernel_workspace/vendor/oplus/secure/biometrics/fingerprints/bsp/drivers_kernel/component3.0/mtk
-          echo "pwd"
-          pwd
-          echo "ls"
-          ls
-          echo "rm Makefile !!!!!!!!"
-          rm Makefile 
-          cat > Makefile <<'EOF'
-          obj-$(CONFIG_OPLUS_FINGERPRINT_COMMON) += oplus_fp_common/
+          for path in \
+            kernel-${{ env.KERNEL_VERSION }}/scripts/setlocalversion; do
 
-          ### Capacitive fingerprint sensor
-          #obj-$(CONFIG_OPLUS_FINGERPRINT_FPC) += fpc/
+            [ -f "$path" ] || continue
 
-          #obj-$(CONFIG_OPLUS_FINGERPRINT_EGIS) += egis/
+            echo "Modifying: $path"
 
-          ### Optical fingerprint sensor
-          ifneq ($(CONFIG_OPLUS_FINGERPRINT_GOODIX)_$(CONFIG_OPLUS_FINGERPRINT_GOODIX_OPTICAL), _)
-          obj-y += goodix_optical_fp/
-          endif
-          #obj-$(CONFIG_OPLUS_FINGERPRINT_SILEAD_OPTICAL) += silead_optical_fp/
-          #obj-$(CONFIG_OPLUS_FINGERPRINT_EGIS_OPTICAL)   += egis_optical_fp/
-          obj-$(CONFIG_OPLUS_FINGERPRINT_JIIOV_OPTICAL)  += anc_driver/
-          obj-$(CONFIG_OPLUS_FINGERPRINT_SILEAD_CAP)  += silead/
+            # Remove -dirty
+            sed -i 's/ -dirty//g' "$path"
+            sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$path"
 
-          ### FEATURE MACRO
-          ccflags-$(CONFIG_OPLUS_FINGERPRINT_NAVIGATION_ENABLE) += -DFP_NAVIGATION_ENABLE
-          EOF
+            if grep -q 'KERNELVERSION.*scm_version' "$path"; then
+              echo "Detected NEW setlocalversion format"
+              sed -i "s|echo \"\${KERNELVERSION}.*scm_version}\"|echo \"\${KERNELVERSION}-${ANDROID_VERSION}-${SUFFIX}\"|" "$path"
 
-      # # Custom kernel suffix
-      # - name: Custom Kernel Suffix if set
-      #   if: ${{ github.event.inputs.SUFFIX != '' }}
-      #   run: |
-      #     cd kernel_workspace
-      #     SUFFIX="${{ github.event.inputs.SUFFIX }}"
-      #     ANDROID_VERSION="${{ env.ANDROID_VERSION }}"
-      #     FAST_BUILD="${{ github.event.inputs.FAST_BUILD }}"
+            elif grep -q 'echo "\$res"' "$path"; then
+              echo "Detected OLD setlocalversion format"
+              if [ "$FAST_BUILD" = "true" ]; then
+                echo "FAST_BUILD enabled: using static res"
+                sed -i "s/^res=.*/res=\"-${ANDROID_VERSION}-${SUFFIX}\"/" "$path"
+              else
+                echo "Standard build: injecting suffix via cut/echo"
+                if [[ -f ./kernel_platform/build_with_bazel.py ]]; then
+                  echo "When using the official script and building with build_with_bazel, the build may fail due to a limit on the number of special characters. Please modify the configuration if that happens."
+                fi
+                tac "$path" | sed "0,/echo \"\\\$res\"/s//res=\\\$(echo \\\$res | cut -d- -f1-2)-${SUFFIX}; echo \"\\\$res\";/" | tac > "$path.tmp" && mv "$path.tmp" "$path"
+              fi
+            else
+              echo "Unknown format, appending echo manually"
+              echo "echo \"\$res-${SUFFIX}\"" >> "$path"
+            fi
 
-      #     for path in \
-      #       kernel_platform/common/scripts/setlocalversion \
-      #       kernel_platform/msm-kernel/scripts/setlocalversion \
-      #       kernel_platform/external/dtc/scripts/setlocalversion; do
+            chmod +x "$path"
+          done
 
-      #       [ -f "$path" ] || continue
-
-      #       echo "Modifying: $path"
-
-      #       # Remove -dirty
-      #       sed -i 's/ -dirty//g' "$path"
-      #       sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$path"
-
-      #       if grep -q 'KERNELVERSION.*scm_version' "$path"; then
-      #         echo "Detected NEW setlocalversion format"
-      #         sed -i "s|echo \"\${KERNELVERSION}.*scm_version}\"|echo \"\${KERNELVERSION}-${ANDROID_VERSION}-${SUFFIX}\"|" "$path"
-
-      #       elif grep -q 'echo "\$res"' "$path"; then
-      #         echo "Detected OLD setlocalversion format"
-      #         if [ "$FAST_BUILD" = "true" ]; then
-      #           echo "FAST_BUILD enabled: using static res"
-      #           sed -i "s/^res=.*/res=\"-${ANDROID_VERSION}-${SUFFIX}\"/" "$path"
-      #         else
-      #           echo "Standard build: injecting suffix via cut/echo"
-      #           if [[ -f ./kernel_platform/build_with_bazel.py ]]; then
-      #             echo "When using the official script and building with build_with_bazel, the build may fail due to a limit on the number of special characters. Please modify the configuration if that happens."
-      #           fi
-      #           tac "$path" | sed "0,/echo \"\\\$res\"/s//res=\\\$(echo \\\$res | cut -d- -f1-2)-${SUFFIX}; echo \"\\\$res\";/" | tac > "$path.tmp" && mv "$path.tmp" "$path"
-      #         fi
-      #       else
-      #         echo "Unknown format, appending echo manually"
-      #         echo "echo \"\$res-${SUFFIX}\"" >> "$path"
-      #       fi
-
-      #       chmod +x "$path"
-      #     done
-
-      #     git add -A
-      #     git commit -m "Custom suffix & removed -dirty"
+          git add -A
+          git commit -m "Custom suffix & removed -dirty"
 
 
       - name: Get Kernel Suffix
@@ -422,33 +324,12 @@ jobs:
             fi
           done
 
-      # - name: Enable lto=thin For FAST
-      #   if: ${{ (env.KERNEL_VERSION == '5.10' || env.KERNEL_VERSION == '5.15') && github.event.inputs.FAST_BUILD == 'true' }}
-      #   run: |
-      #     pwd
-      #     ls
-      #     cd kernel_workspace
-      #     pwd
-      #     ls
-      #     cd kernel-5.10
-      #     ls
-      #     DEFCONFIG=./arch/arm64/configs/gki_defconfig
-      #     echo "Enabling ThinLTO in $DEFCONFIG"
-      #     sed -i 's/^CONFIG_LTO=n/CONFIG_LTO=y/' "$DEFCONFIG"
-      #     sed -i 's/^CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "$DEFCONFIG"
-      #     sed -i 's/^CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "$DEFCONFIG"
-      #     grep -q '^CONFIG_LTO_CLANG_THIN=y' "$DEFCONFIG" || echo 'CONFIG_LTO_CLANG_THIN=y' >> "$DEFCONFIG"
 
       - name: Build Kernel FAST
         if: ${{ github.event.inputs.FAST_BUILD == 'true' }}
         id: fast_build
         run: |
-          # # 1. Set the PATH to the toolchain downloaded by your new manifest
-          # export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/bin:$PATH"
-          # export PATH="/usr/lib/ccache:$PATH"
-          # export CC="ccache clang"
 
-          # # 3. Change to the correct kernel source directory
            echo "cd kernel_workspace/ !!!!!!!!"
            cd kernel_workspace/
            echo "pwd cmd !!!!!!!"
@@ -456,19 +337,6 @@ jobs:
            echo "ls cmd !!!!!!!!!"
            ls
 
-          # # 4. Define the build arguments with corrected paths and syntax
-          # MAKE_ARGS="LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
-          #   PAHOLE=../kernel_platform/prebuilts/kernel-build-tools/linux-x86/bin/pahole \
-          #   LD=/usr/bin/ld.lld HOSTLD=/usr/bin/ld.lld KCFLAGS+='-Wno-error -Wno-error=strict-prototypes'"
-
-          # 5. Add LLVM_IAS if needed for kernel 5.10
-          #if [[ "${{ env.KERNEL_VERSION }}" == "5.10" ]]; then
-          #  MAKE_ARGS="LLVM_IAS=1 $MAKE_ARGS"
-          #fi
-
-          # 6. Run the build
-          # make -j$(nproc --all) O=out $MAKE_ARGS gki_defconfig
-          # make -j$(nproc --all) O=out $MAKE_ARGS
           ./build/build.sh
           ccache -s
 
@@ -477,45 +345,22 @@ jobs:
         run: |
           git clone https://github.com/osm0sis/AnyKernel3.git
 
-          # Correct path to the kernel image from the build step
-          cp kernel_workspace/kernel_platform/common/out/arch/arm64/boot/Image.gz AnyKernel3/
+          # Correct path to the kernel image from the dist directory
+          cp ${{ env.BUILD_OUTPUT_BASE }}/dist/Image.gz AnyKernel3/
 
-          # Correct path to find kernel modules
+          # Correct path to find kernel modules in the kernel-specific output directory
           mkdir -p AnyKernel3/modules
-          find kernel_workspace/kernel_platform/common/out -type f -name "*.ko" -exec cp -f {} AnyKernel3/modules/ \;
+          find ${{ env.BUILD_OUTPUT_BASE }}/kernel-5.10/ -type f -name "*.ko" -exec cp -f {} AnyKernel3/modules/ \;
 
           cd AnyKernel3
-          # Correctly reference the suffix from the step we created
           zip -r9 ../Kernel-OnePlus-Nord-3-${{ steps.suffix_step.outputs.suffix }}.zip * -x .git README.md
+
 
       - name: Set zip Suffix
         id: suffix
         run: |
           echo "value=${{ github.event.inputs.VFS == 'true' && '_VFS' || '' }}${{ github.event.inputs.ZRAM == 'true' && '_LZ4KD' || '' }}${{ github.event.inputs.KPM == 'true' && '_KPM' || '' }}${{ github.event.inputs.SCHED== 'true' && '_SCHED' || '' }}" >> $GITHUB_OUTPUT
 
-      # Get the applicable Android version information from the OnePlus source code.
-      # Note that this is the system Android version, not the kernel Android version you entered.
-      # This step may need to be modified or deleted for non-OnePlus official source code.
-      - name: Auto map FILE to Android version by manifest
-        id: file_clean
-        run: |
-          file="${{ github.event.inputs.FILE }}"
-          cpu="${{ env.CPU }}"
-          xml=".repo/manifests_fallback/${file}.xml"
-          cd $GITHUB_WORKSPACE
-          file_base=$(echo "$file" | sed -E 's/_[a-z]$//')
-          revision_full=$(grep -oP '<project[^>]*name="android_kernel[^"]*"[^>]*revision="\K[^"]+' "$xml" | head -n1 || true)
-          if [ -n "$revision_full" ]; then
-            android_ver=$(echo "$revision_full" | grep -oP '_v?_?\K([0-9]+\.[0-9]+(?:\.[0-9]+)?)' || true)
-            if [ -n "$android_ver" ]; then
-              clean_file="${file_base}_Android${android_ver}"
-            else
-              clean_file="${file_base}_AndroidUnknown"
-            fi
-          else
-            clean_file="${file_base}_AndroidUnknown"
-          fi
-          echo "value=$clean_file" >> "$GITHUB_OUTPUT"
 
       - name: Upload Kernel Zip
         uses: actions/upload-artifact@v4
